#spring:
#  security:
#    user:
#      name: admin
#      password: 89205670641
#  datasource:
#    url: jdbc:postgresql://localhost:5432/security-db
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: 89205670641